project:
  type: website
  output-dir: docs
  resources:
    - images/

execute:
  freeze: auto

website:
  title: "CFM in Zambia"
  navbar:
    left:
      - text: "Introduction"
        href: Introduction.qmd
      - text: "Survey overview"
        href: "CFMG Survey.qmd"
      - text: "Governance"
        href: "CFMG Governance.qmd"
      - text: "Sustainable Forest Management"
        href: "CFMG SFM.qmd"
      - text: "Economic Transformation"
        href: "CFMG ET.qmd"
      - text: "Equity and Inclusion"
        href: "CFMG BS.qmd"
      - text: "Discussion"
        href: Conclusions.qmd
      - text: "Recommendations"
        href: Recommendations.qmd
      - text: "Appendices"
        menu:
          - text: "Appendix I - Methods"
            href: Methods.qmd
          - text: "Appendix II - Survey tool"
            href: Appendix.qmd
          - text: "Appendix III - List of CFs surveyed"
            href: "Appendix II.qmd"

format:
  html:
    toc: true
    toc-location: left
    toc-depth: 3
    theme: cosmo
    css: custom.css
    append-hash: true
    include-after-body: sidebar-footer.html

filters:
  - mcanouil/collapse-output
