project:
  type: book

book:
  title: "Community Forest Management in Zambia: Is It Working?"
  author: "Rhett D Harrison"
  date: "2026"
  chapters:
    - index.qmd
    - Summary.qmd
    - Introduction.qmd
    - Methods.qmd
    - "CFMG Survey.qmd"
    - part: "Results"
      chapters:
        - "CFMG Governance.qmd"
        - "CFMG SFM.qmd"
        - "CFMG ET.qmd"
        - "CFMG BS.qmd"
    - Discussion.qmd
    - Improved_implementation.qmd
    - "Literature cited.qmd"
    - part: "Appendices"
      chapters:
        - Appendix.qmd
        - "Appendix II.qmd"

filters:
  - mcanouil/collapse-output

format:
  html:
    theme: cosmo
    css: custom.css
