---
title: "Appendix"
author: "Rhett D Harrison"
format:
        html:
                css: custom.css
        pdf: default
filters:
- collapse-output
editor: visual
---

## Appendix II - Community forests surveyed

### Community Forest Management in Zambia: Is It Working?

#### List of community forests surveyed and the number of interviews conducted per interview type

```{r}
#| label: Load_data_and_libraries
#| include: false
#| #| warning: false
#| message: false
#| error:   false

library(tidyverse)
library(grid)
library(gt)
library(ggplot2)
library(lme4)
library(lmerTest)
library(emmeans)
library(scales)
library(broom.mixed)
library(modelsummary)
library(ggwordcloud)

load("cfmg.RData")
```

```{r}
#| label: tbl-support_organisations
#| code-fold: true
#| warning: false
#| message: false
#| error:   false
#| tbl-cap: "Community forests surveyed"

cfmg |>
  mutate(interview_type = case_match(
    interview_type,
    "cfmg_executive"       ~ "CFMG Executive",
    "cfmg_female"          ~ "Community Female",
    "cfmg_male"            ~ "Community Male",
    "cfmg_youth"           ~ "Community Youth",
    "individual_interview"  ~ "Individual interviews",
    .default = interview_type
  )) |>
  count(province, cfmg_name, interview_type) |>
  pivot_wider(names_from = interview_type, values_from = n, values_fill = 0) |>
  relocate(`Individual interviews`, .after = last_col()) |>
  mutate(
    cfmg_name = str_to_sentence(cfmg_name)
  ) |>
  arrange(province, cfmg_name) |>
  gt(groupname_col = "province") |>
  cols_label(cfmg_name = "Community forest") |>
  cols_align(align = "left",   columns = cfmg_name) |>
  cols_align(align = "center", columns = where(is.numeric)) |>
  summary_rows(
    groups  = everything(),
    columns = where(is.numeric),
    fns     = list(Total = ~sum(.)),
    fmt     = ~fmt_integer(.)
  ) |>
  grand_summary_rows(
    columns = where(is.numeric),
    fns     = list(`Grand total` = ~sum(.)),
    fmt     = ~fmt_integer(.)
  )


```
